global:
  owner: quickstart-eng@amazon.com
  marketplace-ami: false
  reporting: true
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  cis3bucket:  s3://quickstart-ci-bucket
 
tests:
  quickstart-trendmicro-deepsecurityt1:
    template_file: quickstart-trendmicro-deepsecurity-example1.template
    parameter_input: quickstart-trendmicro-deepsecurity-exampleparms1.json
  quickstart-trendmicro-deepsecurityt2:
    template_file: quickstart-trendmicro-deepsecurity-example2.template
    parameter_input: quickstart-trendmicro-deepsecurity-exampleparms2.json
